# 最初の部分に以下を追加
project 'WidgetApp.xcodeproj'

# Resolve react_native_pods.rb with node to allow for hoisting
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ここを false に変更
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'WidgetApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end

# ウィジェット拡張を別のターゲットとして定義
target 'OshinokoWidgetExtension' do
  platform :ios, min_ios_version_supported
  pod 'WidgetKit'
  
  # RCT関連のポッドを除外
  pod 'React-Core', :modular_headers => true, :configuration => ['Debug', 'Release']
  pod 'React-RCTScrollView', :modular_headers => true, :configuration => ['Debug', 'Release']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
    end
  end
end
